/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-08-29 12:56:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.BoardBean;
import model.BoardDAO;

public final class BoardDeleteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.BoardDAO");
    _jspx_imports_classes.add("model.BoardBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  ");

        BoardDAO bdao = new BoardDAO();
        //String 형식이기 때문에 포장클래스를 사용해서 타입을 변환한다.
        int num = Integer.parseInt(request.getParameter("num"));
 
        //하나의 게시글을 리턴해야하기 때문에 (getOneUpdateBoard메소드를 사용해도 된다.)
        BoardBean bean = bdao.getOneUpdateBoard(num);
    
      out.write("\r\n");
      out.write("    <center>\r\n");
      out.write("        <h2>게시글 삭제</h2>\r\n");
      out.write("        <!-- 패스워드 값을 넘기기때문에 post방식 사용 -->\r\n");
      out.write("        <form action=\"BoardDeleteProc.jsp\" method=\"post\">\r\n");
      out.write("            <table width=\"600\" border=\"1\" bgcolor=\"skyblue\">\r\n");
      out.write("                <tr height=\"40\">\r\n");
      out.write("                    <td width=\"120\" align=\"center\">작성자</td>\r\n");
      out.write("                    <td width=\"180\" align=\"center\">");
      out.print(bean.getWriter());
      out.write("</td>\r\n");
      out.write(" \r\n");
      out.write("                    <td width=\"120\" align=\"center\">작성일</td>\r\n");
      out.write("                    <td width=\"180\" align=\"center\">");
      out.print(bean.getReg_date());
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write(" \r\n");
      out.write("                <tr height=\"40\">\r\n");
      out.write("                    <td width=\"120\" align=\"center\">제목</td>\r\n");
      out.write("                    <td align=\"center\" colspan=\"3\">");
      out.print(bean.getSubject());
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write(" \r\n");
      out.write("                <tr height=\"40\">\r\n");
      out.write("                    <td width=\"120\" align=\"center\">패스워드</td>\r\n");
      out.write("                    <!-- 패스워드는 직접받아야되기때문에 빈에서 받지않는다.-->\r\n");
      out.write("                    <td align=\"Left\" colspan=\"3\"><input type=\"password\"\r\n");
      out.write("                        name=\"password\" size=\"60\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("                <tr height=\"40\">\r\n");
      out.write("                    <td align=\"center\" colspan=\"4\"><input type=\"hidden\" name=\"num\"\r\n");
      out.write("                        value=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("                    <!-- 처리파일에 num값을 그대로 넘겨준다 (삭제하기 위해서) --> <input type=\"submit\"\r\n");
      out.write("                        value=\"글삭제\"> &nbsp;&nbsp; <input type=\"button\"\r\n");
      out.write("                        onclick=\"location.href='BoardList.jsp'\" value=\"목록보기\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
